name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '20.x'

    # Install pnpm
    - run: npm install -g pnpm

    # Install dependencies using pnpm
    - run: pnpm install

    # Build the project
    - run: pnpm run build

    # Deploy using pnpm
    - run: pnpm run deploy:ga
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
